theme: jekyll-theme-architect
exclude:
  - README.md
  - CNAME
keep_files: ["css"]
# Plugins
gems:
  - jekyll-redirect-from

# Front matter defaults
defaults:
  - scope:
      path: "basics"
    values:
      layout: basics
  - scope:
      path: "filters"
    values:
      type: filters
  - scope:
      path: "tags"
    values:
      type: tags
