theme: jekyll-theme-architect
exclude:
  - README.md
  - CNAME
keep_files: ["css"]
# Plugins
gems:
  - jekyll-redirect-from

# Front matter defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "filters"
    values:
      type: filter
  - scope:
      path: "tags"
    values:
      type: tag
